directive @unique on FIELD_DEFINITION

type User {
  _id: ID
  username: String! @unique
  email: String! @unique
  password: String!
  avatar: String
  registerDate: String
  likes: [Post]!
}

type Post {
  _id: ID
  title: String!
  imageUrl: String!
  categories: [String]!
  description: String!
  createdDate: String
  likes: Int
  createdBy: User!
  comments: [Comment]
}

type Comment {
  _id: ID
  commentBody: String!
  commentDate: String
  commentUser: User!
}

type Token {
  token: String!
}

type PostsPage {
  posts: [Post]
  hasMore: Boolean
}

type LikesFaves {
  # Likes for a given post, favorites for users
  likes: Int
  favorites: [Post]
}

type Query {
  getPosts: [Post]
  getPost(postId: ID!): Post!
  getCurrentUser: User
  searchPosts(searchTerm: String): [Post]
  infiniteScrollPosts(pageNum: Int!, pageSize: Int!): PostsPage
}

type Mutation {
  signinUser(username: String!, password: String!): Token
  registerUser(username: String!, email: String!, password: String!): Token
  addPost(
    title: String!
    imageUrl: String!
    categories: [String]!
    description: String!
    creatorId: ID!
  ): Post!
  addPostComment(commentBody: String!, userId: ID!, postId: ID!): Comment!
  likePost(postId: ID!, username: String!): LikesFaves!
  unlikePost(postId: ID!, username: String!): LikesFaves!
}
